version: '3.8'

services:
  # Frontend Production
  frontend:
    image: ${DEPLOY_IMAGE}
    container_name: lineage-frontend-prod
    restart: unless-stopped
    expose:
      - '80'
    networks:
      - lineage-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  lineage-network:
    external: true
    name: lineage-cp-backend_lineage-network
