version: '3.8'

services:
  # Frontend Production
  frontend:
    image: ${DEPLOY_IMAGE}
    container_name: lineage-frontend-prod
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - lineage-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  # Nginx Reverse Proxy for Frontend
  nginx:
    image: nginx:alpine
    container_name: lineage-frontend-nginx-prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
    networks:
      - lineage-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  nginx_logs:
    driver: local

networks:
  lineage-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
