name: Deploy Frontend to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  NODE_VERSION: '20'
  APP_NAME: 'lineage-cp-frontend'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEPLOY_PATH: '/var/www/lineage-cp-frontend'

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Lint code
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Output image
        id: image
        run: echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create Deployment Directory
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p ${{ env.DEPLOY_PATH }}"

      - name: Upload Docker Compose File
        run: |
          echo "Uploading docker-compose.production.yml to server..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp docker-compose.production.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Upload Nginx Configuration
        run: |
          echo "Creating nginx directories on server..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p ${{ env.DEPLOY_PATH }}/nginx/conf.d ${{ env.DEPLOY_PATH }}/nginx/ssl"
          
          echo "Uploading nginx configuration files..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r nginx/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Deploy with Docker
        env:
          DEPLOY_IMAGE: ${{ needs.build.outputs.image }}
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e

            echo "Starting Frontend deployment..."

            cd ${{ env.DEPLOY_PATH }}

            if [ ! -f "docker-compose.production.yml" ]; then
              echo "Error: docker-compose.production.yml not found in ${{ env.DEPLOY_PATH }}"
              exit 1
            fi

            # Set environment variables for Docker Compose
            export DEPLOY_IMAGE="${{ env.DEPLOY_IMAGE }}"

            echo "Pulling Docker image: $DEPLOY_IMAGE"
            docker pull "$DEPLOY_IMAGE"

            echo "Setting up SSL certificates..."
            if [ ! -f "nginx/ssl/fullchain.pem" ] || [ ! -f "nginx/ssl/privkey.pem" ]; then
              echo "Generating self-signed SSL certificate for frontend..."
              mkdir -p nginx/ssl
              openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                -keyout "nginx/ssl/privkey.pem" \
                -out "nginx/ssl/fullchain.pem" \
                -subj "/C=BR/ST=SP/L=SaoPaulo/O=OmegaTeam/CN=omegateam.com.br"
            fi

            echo "Stopping existing containers..."
            docker-compose -f docker-compose.production.yml down || echo "No containers to stop"

            echo "Starting frontend application..."
            docker-compose -f docker-compose.production.yml up -d frontend

            echo "Waiting for frontend to be ready..."
            sleep 10

            echo "Starting nginx proxy..."
            docker-compose -f docker-compose.production.yml up -d nginx

            echo "Waiting for nginx to be ready..."
            sleep 10

            echo "Testing nginx configuration..."
            if docker exec lineage-frontend-nginx-prod nginx -t; then
              echo "✅ Nginx configuration is valid"
            else
              echo "❌ Nginx configuration has errors"
              docker logs lineage-frontend-nginx-prod --tail 20
              exit 1
            fi

            echo "Frontend deployment completed successfully"
          EOF

      - name: Health Check
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e

            echo "Performing frontend health check..."

            sleep 10

            MAX_ATTEMPTS=20
            ATTEMPT=1

            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              echo "Health check attempt $ATTEMPT/$MAX_ATTEMPTS..."

              # Test HTTPS through nginx
              if curl -k -f -s https://localhost/health >/dev/null 2>&1; then
                echo "✅ Frontend HTTPS is working!"
                curl -k -s https://localhost/health
                echo "✅ Frontend is accessible through nginx proxy"
                break
              else
                # If HTTPS fails, let's check what's happening
                echo "HTTPS test failed, checking components..."
                
                # Check if nginx is responding at all
                if curl -f -s http://localhost/ >/dev/null 2>&1; then
                  echo "✅ Nginx is responding on HTTP"
                else
                  echo "❌ Nginx is not responding on HTTP"
                fi
                
                # Check frontend container health
                FRONTEND_HEALTH=$(docker inspect lineage-frontend-prod --format='{{.State.Health.Status}}' 2>/dev/null || echo "unknown")
                echo "Frontend health status: $FRONTEND_HEALTH"
                
                if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
                  echo "❌ Health check failed after $MAX_ATTEMPTS attempts"
                  echo "Frontend logs:"
                  docker logs lineage-frontend-prod --tail 20
                  echo "Nginx logs:"
                  docker logs lineage-frontend-nginx-prod --tail 20
                  echo "Container status:"
                  docker ps
                  exit 1
                fi

                echo "Waiting 5 seconds before next attempt..."
                sleep 5
                ATTEMPT=$((ATTEMPT + 1))
              fi
            done

            echo "Frontend deployment completed successfully!"
          EOF

      - name: Deployment Summary
        run: |
          echo "🎉 Frontend deployment completed!"
          echo "🌐 Frontend URL: https://omegateam.com.br"
          echo "🏥 Health Check: https://omegateam.com.br/health"
